version: '3.8'

services:
  api:
    build:
      context: ./src/FinanceManager.API
      dockerfile: Dockerfile
    image: finance-manager-api:latest
    container_name: finance_api
    ports:
      - '5098:80'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Data Source=/app/data/finance_manager.db
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    image: finance-manager-frontend:latest
    container_name: finance_ui
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: http://localhost:5098


  rabbitmq:
    image: rabbitmq:3-management
    container_name: finance_rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  adminer:
    image: adminer
    container_name: finance_adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: api

networks:
  default:
    driver: bridge
